spring:
    application:
        name: stock

    thymeleaf:
        cache: false # default true, 개발시에는 false로 두는 것이 좋음
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        mode: HTML