spring:
    application:
        name: stock

    thymeleaf:
        cache: false # default true, 개발시에는 false로 두는 것이 좋음
        prefix: classpath:/templates/
        check-template-location: true
        suffix: .html
        mode: HTML

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        generate-ddl: false

    datasource:
        url: jdbc:postgresql://${POSTGRESQL_HOST}:5432/stock
        username: ${POSTGRESQL_USER}
        password: ${POSTGRESQL_PASSWORD}
        driver-class-name: org.postgresql.Driver
